# Generated by Django 2.1.7 on 2019-02-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('rollno', models.IntegerField(primary_key=True, serialize=False)),
                ('classid', models.CharField(max_length=10)),
                ('semester', models.IntegerField()),
                ('last_online', models.DateField(auto_now=True)),
                ('cr', models.BooleanField()),
            ],
        ),
    ]
