# Generated by Django 2.1.7 on 2019-04-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dev_id',
            field=models.CharField(default='0:0:0:0', max_length=40),
            preserve_default=False,
        ),
    ]
