# Generated by Django 2.1.7 on 2019-03-04 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20190304_1852'),
        ('crtools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('start_hour', models.IntegerField()),
                ('deleted', models.BooleanField(default=False)),
                ('lab_course', models.BooleanField(default=False)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Course')),
            ],
        ),
    ]
