# Generated by Django 2.1.7 on 2019-03-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crtools', '0004_remove_reminder_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttchange',
            name='course_name',
            field=models.CharField(default='def', max_length=40),
            preserve_default=False,
        ),
    ]
