# Generated by Django 2.1.7 on 2019-03-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crtools', '0005_ttchange_course_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ttchange',
            old_name='lab_course',
            new_name='lab_hour',
        ),
        migrations.RemoveField(
            model_name='ttchange',
            name='course_name',
        ),
        migrations.AlterField(
            model_name='ttchange',
            name='date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ttchange',
            name='start_hour',
            field=models.IntegerField(default=0),
        ),
    ]
