# Generated by Django 2.1.7 on 2019-03-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crtools', '0006_auto_20190305_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttchange',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
