# Generated by Django 2.1.7 on 2019-02-23 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_name', models.CharField(max_length=40)),
                ('course_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_semester', models.IntegerField(default=0)),
                ('course_credits', models.IntegerField(default=0)),
                ('lectures', models.IntegerField(default=0)),
                ('labs', models.IntegerField(default=0)),
                ('num_classes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes_bunked', models.IntegerField(default=0)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Student')),
            ],
        ),
        migrations.CreateModel(
            name='TTFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.IntegerField(default=0)),
                ('day', models.DateField()),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Course')),
            ],
        ),
    ]
