# Generated by Django 2.1.7 on 2019-03-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='class_id',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ttformat',
            name='lab_hour',
            field=models.BooleanField(default=False),
        ),
    ]
