# Generated by Django 2.1.7 on 2019-03-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20190304_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolled',
            name='bunk_percentage',
            field=models.FloatField(default=0),
        ),
    ]
