# Generated by Django 2.1.7 on 2019-03-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_enrolled_bunk_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='num_classes',
            field=models.IntegerField(default=1),
        ),
    ]
