# Generated by Django 2.1.7 on 2019-04-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20190305_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolled',
            name='official_classes_bunked',
            field=models.IntegerField(default=0),
        ),
    ]
