# Generated by Django 2.1.7 on 2019-04-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('timetable', '0006_enrolled_official_classes_bunked'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=models.SET(0), to='teacher.TeacherAcc'),
            preserve_default=False,
        ),
    ]
